name: example
description: A new Flutter project.

publish_to: 'none'

version: 0.1.0

environment:
  sdk: ">=2.8.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  gallery_media_picker:
    path: ../
  provider: ^6.0.3
  photo_view: ^0.14.0
  better_video_player: ^1.2.8
  share_plus: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true
